/*
 * Every symbol caiman's /vendor/lib64/libOpenCL.so exports, for
 * vendor_forward.c.  Google Camera late-binds OpenCL through dlsym() and calls
 * what it finds without a null check: against an empty stub the first call,
 * clGetPlatformIDs(0, NULL, &n), branches to address 0.
 *
 * Generated from the device's own library:
 *   readelf -sDW /vendor/lib64/libOpenCL.so, last column, version suffix cut
 */

#define ATL_VENDOR_SYMBOL_LIST(X) \
	X(clBuildProgram) \
	X(clCloneKernel) \
	X(clCompileProgram) \
	X(clCreateBuffer) \
	X(clCreateBufferWithProperties) \
	X(clCreateCommandQueue) \
	X(clCreateCommandQueueWithProperties) \
	X(clCreateContext) \
	X(clCreateContextFromType) \
	X(clCreateFromGLBuffer) \
	X(clCreateFromGLRenderbuffer) \
	X(clCreateFromGLTexture) \
	X(clCreateFromGLTexture2D) \
	X(clCreateFromGLTexture3D) \
	X(clCreateImage) \
	X(clCreateImage2D) \
	X(clCreateImage3D) \
	X(clCreateImageWithProperties) \
	X(clCreateKernel) \
	X(clCreateKernelsInProgram) \
	X(clCreatePipe) \
	X(clCreateProgramWithBinary) \
	X(clCreateProgramWithBuiltInKernels) \
	X(clCreateProgramWithIL) \
	X(clCreateProgramWithSource) \
	X(clCreateSampler) \
	X(clCreateSamplerWithProperties) \
	X(clCreateSubBuffer) \
	X(clCreateSubDevices) \
	X(clCreateUserEvent) \
	X(clEnqueueAcquireGLObjects) \
	X(clEnqueueBarrier) \
	X(clEnqueueBarrierWithWaitList) \
	X(clEnqueueCopyBuffer) \
	X(clEnqueueCopyBufferRect) \
	X(clEnqueueCopyBufferToImage) \
	X(clEnqueueCopyImage) \
	X(clEnqueueCopyImageToBuffer) \
	X(clEnqueueFillBuffer) \
	X(clEnqueueFillImage) \
	X(clEnqueueMapBuffer) \
	X(clEnqueueMapImage) \
	X(clEnqueueMarker) \
	X(clEnqueueMarkerWithWaitList) \
	X(clEnqueueMigrateMemObjects) \
	X(clEnqueueNativeKernel) \
	X(clEnqueueNDRangeKernel) \
	X(clEnqueueReadBuffer) \
	X(clEnqueueReadBufferRect) \
	X(clEnqueueReadImage) \
	X(clEnqueueReleaseGLObjects) \
	X(clEnqueueSVMFree) \
	X(clEnqueueSVMMap) \
	X(clEnqueueSVMMemcpy) \
	X(clEnqueueSVMMemFill) \
	X(clEnqueueSVMMigrateMem) \
	X(clEnqueueSVMUnmap) \
	X(clEnqueueTask) \
	X(clEnqueueUnmapMemObject) \
	X(clEnqueueWaitForEvents) \
	X(clEnqueueWriteBuffer) \
	X(clEnqueueWriteBufferRect) \
	X(clEnqueueWriteImage) \
	X(clFinish) \
	X(clFlush) \
	X(clGetCommandQueueInfo) \
	X(clGetContextInfo) \
	X(clGetDeviceAndHostTimer) \
	X(clGetDeviceIDs) \
	X(clGetDeviceInfo) \
	X(clGetEventInfo) \
	X(clGetEventProfilingInfo) \
	X(clGetExtensionFunctionAddress) \
	X(clGetExtensionFunctionAddressForPlatform) \
	X(clGetGLObjectInfo) \
	X(clGetGLTextureInfo) \
	X(clGetHostTimer) \
	X(clGetImageInfo) \
	X(clGetKernelArgInfo) \
	X(clGetKernelInfo) \
	X(clGetKernelSubGroupInfo) \
	X(clGetKernelWorkGroupInfo) \
	X(clGetMemObjectInfo) \
	X(clGetPipeInfo) \
	X(clGetPlatformIDs) \
	X(clGetPlatformInfo) \
	X(clGetProgramBuildInfo) \
	X(clGetProgramInfo) \
	X(clGetSamplerInfo) \
	X(clGetSupportedImageFormats) \
	X(clLinkProgram) \
	X(clReleaseCommandQueue) \
	X(clReleaseContext) \
	X(clReleaseDevice) \
	X(clReleaseEvent) \
	X(clReleaseKernel) \
	X(clReleaseMemObject) \
	X(clReleaseProgram) \
	X(clReleaseSampler) \
	X(clRetainCommandQueue) \
	X(clRetainContext) \
	X(clRetainDevice) \
	X(clRetainEvent) \
	X(clRetainKernel) \
	X(clRetainMemObject) \
	X(clRetainProgram) \
	X(clRetainSampler) \
	X(clSetCommandQueueProperty) \
	X(clSetContextDestructorCallback) \
	X(clSetDefaultDeviceCommandQueue) \
	X(clSetEventCallback) \
	X(clSetKernelArg) \
	X(clSetKernelArgSVMPointer) \
	X(clSetKernelExecInfo) \
	X(clSetMemObjectDestructorCallback) \
	X(clSetProgramReleaseCallback) \
	X(clSetProgramSpecializationConstant) \
	X(clSetUserEventStatus) \
	X(clSVMAlloc) \
	X(clSVMFree) \
	X(clUnloadCompiler) \
	X(clUnloadPlatformCompiler) \
	X(clWaitForEvents)
