/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_RadialGradient */

#ifndef _Included_android_graphics_RadialGradient
#define _Included_android_graphics_RadialGradient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_RadialGradient
 * Method:    native_create
 * Signature: (FFF[I[FI)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_RadialGradient_native_1create
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jintArray, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
