/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_view_ViewRootImpl */

#ifndef _Included_android_view_ViewRootImpl
#define _Included_android_view_ViewRootImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef android_view_ViewRootImpl_LIGHT_Z_DP
#define android_view_ViewRootImpl_LIGHT_Z_DP 500.0f
#undef android_view_ViewRootImpl_LIGHT_RADIUS_DP
#define android_view_ViewRootImpl_LIGHT_RADIUS_DP 800.0f
#undef android_view_ViewRootImpl_AMBIENT_SHADOW_COLOR
#define android_view_ViewRootImpl_AMBIENT_SHADOW_COLOR 167772160L
#undef android_view_ViewRootImpl_SPOT_SHADOW_COLOR
#define android_view_ViewRootImpl_SPOT_SHADOW_COLOR 805306368L
/*
 * Class:     android_view_ViewRootImpl
 * Method:    nativeInvalidate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_view_ViewRootImpl_nativeInvalidate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_view_ViewRootImpl
 * Method:    nativeRequestLayout
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_view_ViewRootImpl_nativeRequestLayout
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
