/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Typeface */

#ifndef _Included_android_graphics_Typeface
#define _Included_android_graphics_Typeface
#ifdef __cplusplus
extern "C" {
#endif
#undef android_graphics_Typeface_NORMAL
#define android_graphics_Typeface_NORMAL 0L
#undef android_graphics_Typeface_BOLD
#define android_graphics_Typeface_BOLD 1L
#undef android_graphics_Typeface_ITALIC
#define android_graphics_Typeface_ITALIC 2L
#undef android_graphics_Typeface_BOLD_ITALIC
#define android_graphics_Typeface_BOLD_ITALIC 3L
#undef android_graphics_Typeface_RESOLVE_BY_FONT_TABLE
#define android_graphics_Typeface_RESOLVE_BY_FONT_TABLE -1L
/*
 * Class:     android_graphics_Typeface
 * Method:    nativeCreateNamed
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Typeface_nativeCreateNamed
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     android_graphics_Typeface
 * Method:    nativeCreateRelative
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Typeface_nativeCreateRelative
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_Typeface
 * Method:    nativeCreateFromTypefaceWithExactStyle
 * Signature: (JIZ)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Typeface_nativeCreateFromTypefaceWithExactStyle
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     android_graphics_Typeface
 * Method:    nativeCreateFromFile
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Typeface_nativeCreateFromFile
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     android_graphics_Typeface
 * Method:    nativeGetStyle
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Typeface_nativeGetStyle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Typeface
 * Method:    nativeGetWeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Typeface_nativeGetWeight
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
