/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_BitmapShader */

#ifndef _Included_android_graphics_BitmapShader
#define _Included_android_graphics_BitmapShader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_BitmapShader
 * Method:    native_create
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_BitmapShader_native_1create
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
