/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Region */

#ifndef _Included_android_graphics_Region
#define _Included_android_graphics_Region
#ifdef __cplusplus
extern "C" {
#endif
#undef android_graphics_Region_MAX_POOL_SIZE
#define android_graphics_Region_MAX_POOL_SIZE 10L
/*
 * Class:     android_graphics_Region
 * Method:    isEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_isEmpty
  (JNIEnv *, jobject);

/*
 * Class:     android_graphics_Region
 * Method:    isRect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_isRect
  (JNIEnv *, jobject);

/*
 * Class:     android_graphics_Region
 * Method:    isComplex
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_isComplex
  (JNIEnv *, jobject);

/*
 * Class:     android_graphics_Region
 * Method:    contains
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_contains
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     android_graphics_Region
 * Method:    quickContains
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_quickContains
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     android_graphics_Region
 * Method:    quickReject
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_quickReject__IIII
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     android_graphics_Region
 * Method:    quickReject
 * Signature: (Landroid/graphics/Region;)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_quickReject__Landroid_graphics_Region_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     android_graphics_Region
 * Method:    translate
 * Signature: (IILandroid/graphics/Region;)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Region_translate
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     android_graphics_Region
 * Method:    scale
 * Signature: (FLandroid/graphics/Region;)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Region_scale
  (JNIEnv *, jobject, jfloat, jobject);

/*
 * Class:     android_graphics_Region
 * Method:    nativeEquals
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeEquals
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Region
 * Method:    nativeConstructor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Region_nativeConstructor
  (JNIEnv *, jclass);

/*
 * Class:     android_graphics_Region
 * Method:    nativeDestructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Region_nativeDestructor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Region
 * Method:    nativeSetRegion
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Region_nativeSetRegion
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Region
 * Method:    nativeSetRect
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeSetRect
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     android_graphics_Region
 * Method:    nativeSetPath
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeSetPath
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     android_graphics_Region
 * Method:    nativeGetBounds
 * Signature: (JLandroid/graphics/Rect;)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeGetBounds
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     android_graphics_Region
 * Method:    nativeGetBoundaryPath
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeGetBoundaryPath
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Region
 * Method:    nativeOp
 * Signature: (JIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeOp__JIIIII
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     android_graphics_Region
 * Method:    nativeOp
 * Signature: (JLandroid/graphics/Rect;JI)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeOp__JLandroid_graphics_Rect_2JI
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     android_graphics_Region
 * Method:    nativeOp
 * Signature: (JJJI)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Region_nativeOp__JJJI
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     android_graphics_Region
 * Method:    nativeToString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_graphics_Region_nativeToString
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
