/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Canvas */

#ifndef _Included_android_graphics_Canvas
#define _Included_android_graphics_Canvas
#ifdef __cplusplus
extern "C" {
#endif
#undef android_graphics_Canvas_MAXMIMUM_BITMAP_SIZE
#define android_graphics_Canvas_MAXMIMUM_BITMAP_SIZE 32766L
#undef android_graphics_Canvas_MATRIX_SAVE_FLAG
#define android_graphics_Canvas_MATRIX_SAVE_FLAG 1L
#undef android_graphics_Canvas_CLIP_SAVE_FLAG
#define android_graphics_Canvas_CLIP_SAVE_FLAG 2L
#undef android_graphics_Canvas_HAS_ALPHA_LAYER_SAVE_FLAG
#define android_graphics_Canvas_HAS_ALPHA_LAYER_SAVE_FLAG 4L
#undef android_graphics_Canvas_FULL_COLOR_LAYER_SAVE_FLAG
#define android_graphics_Canvas_FULL_COLOR_LAYER_SAVE_FLAG 8L
#undef android_graphics_Canvas_CLIP_TO_LAYER_SAVE_FLAG
#define android_graphics_Canvas_CLIP_TO_LAYER_SAVE_FLAG 16L
#undef android_graphics_Canvas_ALL_SAVE_FLAG
#define android_graphics_Canvas_ALL_SAVE_FLAG 31L
/*
 * Class:     android_graphics_Canvas
 * Method:    nDrawNinePatch
 * Signature: (JJJFFFFJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nDrawNinePatch
  (JNIEnv *, jclass, jlong, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nFreeCaches
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nFreeCaches
  (JNIEnv *, jclass);

/*
 * Class:     android_graphics_Canvas
 * Method:    nFreeTextLayoutCaches
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nFreeTextLayoutCaches
  (JNIEnv *, jclass);

/*
 * Class:     android_graphics_Canvas
 * Method:    nGetNativeFinalizer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Canvas_nGetNativeFinalizer
  (JNIEnv *, jclass);

/*
 * Class:     android_graphics_Canvas
 * Method:    nSetCompatibilityVersion
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nSetCompatibilityVersion
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_graphics_Canvas
 * Method:    nInitRaster
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Canvas_nInitRaster
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nSetBitmap
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nSetBitmap
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nGetClipBounds
 * Signature: (JLandroid/graphics/Rect;)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Canvas_nGetClipBounds
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     android_graphics_Canvas
 * Method:    nIsOpaque
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Canvas_nIsOpaque
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nGetWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Canvas_nGetWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nGetHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Canvas_nGetHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nSave
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Canvas_nSave
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_Canvas
 * Method:    nSaveLayer
 * Signature: (JFFFFJ)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Canvas_nSaveLayer
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nSaveLayerAlpha
 * Signature: (JFFFFI)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Canvas_nSaveLayerAlpha
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     android_graphics_Canvas
 * Method:    nSaveUnclippedLayer
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Canvas_nSaveUnclippedLayer
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     android_graphics_Canvas
 * Method:    nRestoreUnclippedLayer
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nRestoreUnclippedLayer
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nRestore
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Canvas_nRestore
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nRestoreToCount
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nRestoreToCount
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_Canvas
 * Method:    nGetSaveCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Canvas_nGetSaveCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nTranslate
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nTranslate
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Canvas
 * Method:    nScale
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nScale
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Canvas
 * Method:    nRotate
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nRotate
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     android_graphics_Canvas
 * Method:    nSkew
 * Signature: (JFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nSkew
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     android_graphics_Canvas
 * Method:    nConcat
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nConcat
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nSetMatrix
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nSetMatrix
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nClipRect
 * Signature: (JFFFFI)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Canvas_nClipRect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     android_graphics_Canvas
 * Method:    nClipPath
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Canvas_nClipPath
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     android_graphics_Canvas
 * Method:    nSetDrawFilter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nSetDrawFilter
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nGetMatrix
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nGetMatrix
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nQuickReject
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Canvas_nQuickReject__JJ
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_Canvas
 * Method:    nQuickReject
 * Signature: (JFFFF)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_Canvas_nQuickReject__JFFFF
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     android_graphics_Canvas
 * Method:    nDrawRenderNode
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Canvas_nDrawRenderNode
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
