/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_text_MeasuredText */

#ifndef _Included_android_graphics_text_MeasuredText
#define _Included_android_graphics_text_MeasuredText
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_text_MeasuredText
 * Method:    nGetWidth
 * Signature: (JII)F
 */
JNIEXPORT jfloat JNICALL Java_android_graphics_text_MeasuredText_nGetWidth
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     android_graphics_text_MeasuredText
 * Method:    nGetReleaseFunc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_text_MeasuredText_nGetReleaseFunc
  (JNIEnv *, jclass);

/*
 * Class:     android_graphics_text_MeasuredText
 * Method:    nGetMemoryUsage
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_text_MeasuredText_nGetMemoryUsage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_text_MeasuredText
 * Method:    nGetBounds
 * Signature: (J[CIILandroid/graphics/Rect;)V
 */
JNIEXPORT void JNICALL Java_android_graphics_text_MeasuredText_nGetBounds
  (JNIEnv *, jclass, jlong, jcharArray, jint, jint, jobject);

/*
 * Class:     android_graphics_text_MeasuredText
 * Method:    nGetCharWidthAt
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_android_graphics_text_MeasuredText_nGetCharWidthAt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_text_MeasuredText
 * Method:    nGetExtent
 * Signature: (J[CII)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_text_MeasuredText_nGetExtent
  (JNIEnv *, jclass, jlong, jcharArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
