/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_NinePatch */

#ifndef _Included_android_graphics_NinePatch
#define _Included_android_graphics_NinePatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_NinePatch
 * Method:    nativeReadChunkFromFile
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_android_graphics_NinePatch_nativeReadChunkFromFile
  (JNIEnv *, jclass, jstring);

/*
 * Class:     android_graphics_NinePatch
 * Method:    isNinePatchChunk
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_NinePatch_isNinePatchChunk
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     android_graphics_NinePatch
 * Method:    validateNinePatchChunk
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_NinePatch_validateNinePatchChunk
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     android_graphics_NinePatch
 * Method:    nativeFinalize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_NinePatch_nativeFinalize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_NinePatch
 * Method:    nativeGetPadding
 * Signature: (JLandroid/graphics/Rect;)V
 */
JNIEXPORT void JNICALL Java_android_graphics_NinePatch_nativeGetPadding
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
