/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_app_Activity */

#ifndef _Included_android_app_Activity
#define _Included_android_app_Activity
#ifdef __cplusplus
extern "C" {
#endif
#undef android_app_Activity_MODE_PRIVATE
#define android_app_Activity_MODE_PRIVATE 0L
#undef android_app_Activity_CONTEXT_INCLUDE_CODE
#define android_app_Activity_CONTEXT_INCLUDE_CODE 1L
#undef android_app_Activity_CONTEXT_IGNORE_SECURITY
#define android_app_Activity_CONTEXT_IGNORE_SECURITY 2L
#undef android_app_Activity_CONTEXT_RESTRICTED
#define android_app_Activity_CONTEXT_RESTRICTED 4L
#undef android_app_Activity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define android_app_Activity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef android_app_Activity_MODE_NO_LOCALIZED_COLLATORS
#define android_app_Activity_MODE_NO_LOCALIZED_COLLATORS 16L
#undef android_app_Activity_BIND_AUTO_CREATE
#define android_app_Activity_BIND_AUTO_CREATE 1L
#undef android_app_Activity_BIND_IMPORTANT
#define android_app_Activity_BIND_IMPORTANT 64L
#undef android_app_Activity_BIND_WAIVE_PRIORITY
#define android_app_Activity_BIND_WAIVE_PRIORITY 32L
#undef android_app_Activity_RESULT_CANCELED
#define android_app_Activity_RESULT_CANCELED 0L
#undef android_app_Activity_RESULT_OK
#define android_app_Activity_RESULT_OK -1L
#undef android_app_Activity_LIFECYCLE_PRE
#define android_app_Activity_LIFECYCLE_PRE 0L
#undef android_app_Activity_LIFECYCLE_ON
#define android_app_Activity_LIFECYCLE_ON 1L
#undef android_app_Activity_LIFECYCLE_POST
#define android_app_Activity_LIFECYCLE_POST 2L
#undef android_app_Activity_LIFECYCLE_CREATE
#define android_app_Activity_LIFECYCLE_CREATE 0L
#undef android_app_Activity_LIFECYCLE_START
#define android_app_Activity_LIFECYCLE_START 1L
#undef android_app_Activity_LIFECYCLE_RESUME
#define android_app_Activity_LIFECYCLE_RESUME 2L
#undef android_app_Activity_LIFECYCLE_PAUSE
#define android_app_Activity_LIFECYCLE_PAUSE 3L
#undef android_app_Activity_LIFECYCLE_STOP
#define android_app_Activity_LIFECYCLE_STOP 4L
#undef android_app_Activity_LIFECYCLE_DESTROY
#define android_app_Activity_LIFECYCLE_DESTROY 5L
#undef android_app_Activity_LIFECYCLE_SAVE_INSTANCE_STATE
#define android_app_Activity_LIFECYCLE_SAVE_INSTANCE_STATE 6L
/*
 * Class:     android_app_Activity
 * Method:    isTaskRoot
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_app_Activity_isTaskRoot
  (JNIEnv *, jobject);

/*
 * Class:     android_app_Activity
 * Method:    nativeFinish
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_app_Activity_nativeFinish
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_app_Activity
 * Method:    nativeStartActivity
 * Signature: (Landroid/app/Activity;)V
 */
JNIEXPORT void JNICALL Java_android_app_Activity_nativeStartActivity
  (JNIEnv *, jclass, jobject);

/*
 * Class:     android_app_Activity
 * Method:    nativeResumeActivity
 * Signature: (Ljava/lang/Class;Landroid/content/Intent;)Z
 */
JNIEXPORT jboolean JNICALL Java_android_app_Activity_nativeResumeActivity
  (JNIEnv *, jclass, jclass, jobject);

/*
 * Class:     android_app_Activity
 * Method:    nativeOpenURI
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_app_Activity_nativeOpenURI
  (JNIEnv *, jclass, jstring);

/*
 * Class:     android_app_Activity
 * Method:    isInMultiWindowMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_app_Activity_isInMultiWindowMode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
