/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_SurfaceTexture */

#ifndef _Included_android_graphics_SurfaceTexture
#define _Included_android_graphics_SurfaceTexture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_SurfaceTexture
 * Method:    native_create
 * Signature: (IZZ)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_SurfaceTexture_native_1create
  (JNIEnv *, jobject, jint, jboolean, jboolean);

/*
 * Class:     android_graphics_SurfaceTexture
 * Method:    native_release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_SurfaceTexture_native_1release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_graphics_SurfaceTexture
 * Method:    native_setFrameAvailableEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_SurfaceTexture_native_1setFrameAvailableEnabled
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     android_graphics_SurfaceTexture
 * Method:    native_setDefaultBufferSize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_android_graphics_SurfaceTexture_native_1setDefaultBufferSize
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     android_graphics_SurfaceTexture
 * Method:    native_updateTexImage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_SurfaceTexture_native_1updateTexImage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_graphics_SurfaceTexture
 * Method:    native_attachToGLContext
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_SurfaceTexture_native_1attachToGLContext
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     android_graphics_SurfaceTexture
 * Method:    native_getTransformMatrix
 * Signature: (J[F)V
 */
JNIEXPORT void JNICALL Java_android_graphics_SurfaceTexture_native_1getTransformMatrix
  (JNIEnv *, jobject, jlong, jfloatArray);

/*
 * Class:     android_graphics_SurfaceTexture
 * Method:    native_getTimestamp
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_SurfaceTexture_native_1getTimestamp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_graphics_SurfaceTexture
 * Method:    native_getLatestFrameBitmap
 * Signature: (J)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_android_graphics_SurfaceTexture_native_1getLatestFrameBitmap
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
