/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_RegionIterator */

#ifndef _Included_android_graphics_RegionIterator
#define _Included_android_graphics_RegionIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_RegionIterator
 * Method:    nativeConstructor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_RegionIterator_nativeConstructor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_RegionIterator
 * Method:    nativeDestructor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_RegionIterator_nativeDestructor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_RegionIterator
 * Method:    nativeNext
 * Signature: (JLandroid/graphics/Rect;)Z
 */
JNIEXPORT jboolean JNICALL Java_android_graphics_RegionIterator_nativeNext
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
