/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_text_MeasuredText_Builder */

#ifndef _Included_android_graphics_text_MeasuredText_Builder
#define _Included_android_graphics_text_MeasuredText_Builder
#ifdef __cplusplus
extern "C" {
#endif
#undef android_graphics_text_MeasuredText_Builder_HYPHENATION_MODE_NONE
#define android_graphics_text_MeasuredText_Builder_HYPHENATION_MODE_NONE 0L
#undef android_graphics_text_MeasuredText_Builder_HYPHENATION_MODE_NORMAL
#define android_graphics_text_MeasuredText_Builder_HYPHENATION_MODE_NORMAL 1L
#undef android_graphics_text_MeasuredText_Builder_HYPHENATION_MODE_FAST
#define android_graphics_text_MeasuredText_Builder_HYPHENATION_MODE_FAST 2L
/*
 * Class:     android_graphics_text_MeasuredText_Builder
 * Method:    nInitBuilder
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_text_MeasuredText_00024Builder_nInitBuilder
  (JNIEnv *, jclass);

/*
 * Class:     android_graphics_text_MeasuredText_Builder
 * Method:    nAddStyleRun
 * Signature: (JJIIIIZ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_text_MeasuredText_00024Builder_nAddStyleRun
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jint, jint, jboolean);

/*
 * Class:     android_graphics_text_MeasuredText_Builder
 * Method:    nAddReplacementRun
 * Signature: (JJIIF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_text_MeasuredText_00024Builder_nAddReplacementRun
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jfloat);

/*
 * Class:     android_graphics_text_MeasuredText_Builder
 * Method:    nBuildMeasuredText
 * Signature: (JJ[CZZZ)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_text_MeasuredText_00024Builder_nBuildMeasuredText
  (JNIEnv *, jclass, jlong, jlong, jcharArray, jboolean, jboolean, jboolean);

/*
 * Class:     android_graphics_text_MeasuredText_Builder
 * Method:    nFreeBuilder
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_text_MeasuredText_00024Builder_nFreeBuilder
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
