/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_app_WallpaperManager */

#ifndef _Included_android_app_WallpaperManager
#define _Included_android_app_WallpaperManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_app_WallpaperManager
 * Method:    set_wallpaper
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_android_app_WallpaperManager_set_1wallpaper
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
