/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_media_MediaRecorder */

#ifndef _Included_android_media_MediaRecorder
#define _Included_android_media_MediaRecorder
#ifdef __cplusplus
extern "C" {
#endif
#undef android_media_MediaRecorder_MEDIA_RECORDER_INFO_MAX_DURATION_REACHED
#define android_media_MediaRecorder_MEDIA_RECORDER_INFO_MAX_DURATION_REACHED 800L
#undef android_media_MediaRecorder_MEDIA_RECORDER_INFO_MAX_FILESIZE_REACHED
#define android_media_MediaRecorder_MEDIA_RECORDER_INFO_MAX_FILESIZE_REACHED 801L
/*
 * Class:     android_media_MediaRecorder
 * Method:    native_prepare
 * Signature: (IIIILjava/lang/String;Landroid/view/Surface;)J
 */
JNIEXPORT jlong JNICALL Java_android_media_MediaRecorder_native_1prepare
  (JNIEnv *, jclass, jint, jint, jint, jint, jstring, jobject);

/*
 * Class:     android_media_MediaRecorder
 * Method:    native_start
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_media_MediaRecorder_native_1start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_MediaRecorder
 * Method:    native_stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_media_MediaRecorder_native_1stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_MediaRecorder
 * Method:    native_frameCount
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_media_MediaRecorder_native_1frameCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_MediaRecorder
 * Method:    native_release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_media_MediaRecorder_native_1release
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
