/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_media_MediaMuxer */

#ifndef _Included_android_media_MediaMuxer
#define _Included_android_media_MediaMuxer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_media_MediaMuxer
 * Method:    native_create
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_android_media_MediaMuxer_native_1create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     android_media_MediaMuxer
 * Method:    native_addTrack
 * Signature: (JIIILjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_android_media_MediaMuxer_native_1addTrack
  (JNIEnv *, jclass, jlong, jint, jint, jint, jobject);

/*
 * Class:     android_media_MediaMuxer
 * Method:    native_setOrientation
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_media_MediaMuxer_native_1setOrientation
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_media_MediaMuxer
 * Method:    native_start
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_media_MediaMuxer_native_1start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_MediaMuxer
 * Method:    native_write
 * Signature: (JLjava/nio/ByteBuffer;IJZ)V
 */
JNIEXPORT void JNICALL Java_android_media_MediaMuxer_native_1write
  (JNIEnv *, jclass, jlong, jobject, jint, jlong, jboolean);

/*
 * Class:     android_media_MediaMuxer
 * Method:    native_stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_media_MediaMuxer_native_1stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_MediaMuxer
 * Method:    native_release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_media_MediaMuxer_native_1release
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
