/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_net_ConnectivityManager */

#ifndef _Included_android_net_ConnectivityManager
#define _Included_android_net_ConnectivityManager
#ifdef __cplusplus
extern "C" {
#endif
#undef android_net_ConnectivityManager_TYPE_BLUETOOTH
#define android_net_ConnectivityManager_TYPE_BLUETOOTH 7L
#undef android_net_ConnectivityManager_TYPE_ETHERNET
#define android_net_ConnectivityManager_TYPE_ETHERNET 9L
#undef android_net_ConnectivityManager_TYPE_MOBILE
#define android_net_ConnectivityManager_TYPE_MOBILE 0L
#undef android_net_ConnectivityManager_TYPE_WIFI
#define android_net_ConnectivityManager_TYPE_WIFI 1L
#undef android_net_ConnectivityManager_TYPE_WIMAX
#define android_net_ConnectivityManager_TYPE_WIMAX 6L
#undef android_net_ConnectivityManager_RESTRICT_BACKGROUND_STATUS_DISABLED
#define android_net_ConnectivityManager_RESTRICT_BACKGROUND_STATUS_DISABLED 1L
#undef android_net_ConnectivityManager_RESTRICT_BACKGROUND_STATUS_WHITELISTED
#define android_net_ConnectivityManager_RESTRICT_BACKGROUND_STATUS_WHITELISTED 2L
#undef android_net_ConnectivityManager_RESTRICT_BACKGROUND_STATUS_ENABLED
#define android_net_ConnectivityManager_RESTRICT_BACKGROUND_STATUS_ENABLED 3L
/*
 * Class:     android_net_ConnectivityManager
 * Method:    registerNetworkCallback
 * Signature: (Landroid/net/NetworkRequest;Landroid/net/ConnectivityManager/NetworkCallback;)V
 */
JNIEXPORT void JNICALL Java_android_net_ConnectivityManager_registerNetworkCallback
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     android_net_ConnectivityManager
 * Method:    isActiveNetworkMetered
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_net_ConnectivityManager_isActiveNetworkMetered
  (JNIEnv *, jobject);

/*
 * Class:     android_net_ConnectivityManager
 * Method:    nativeGetNetworkAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_net_ConnectivityManager_nativeGetNetworkAvailable
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
