/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_media_ImageWriter */

#ifndef _Included_android_media_ImageWriter
#define _Included_android_media_ImageWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_media_ImageWriter
 * Method:    native_fromSurface
 * Signature: (Landroid/view/Surface;Landroid/media/ImageWriter;)J
 */
JNIEXPORT jlong JNICALL Java_android_media_ImageWriter_native_1fromSurface
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     android_media_ImageWriter
 * Method:    native_info
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_android_media_ImageWriter_native_1info
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_ImageWriter
 * Method:    native_dequeue
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_media_ImageWriter_native_1dequeue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_ImageWriter
 * Method:    native_queueOwn
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_media_ImageWriter_native_1queueOwn
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     android_media_ImageWriter
 * Method:    native_queueForeign
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_media_ImageWriter_native_1queueForeign
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_media_ImageWriter
 * Method:    native_planeInfo
 * Signature: (JI)[I
 */
JNIEXPORT jintArray JNICALL Java_android_media_ImageWriter_native_1planeInfo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_media_ImageWriter
 * Method:    native_planeBuffer
 * Signature: (JII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_android_media_ImageWriter_native_1planeBuffer
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     android_media_ImageWriter
 * Method:    native_cancel
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_media_ImageWriter_native_1cancel
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_media_ImageWriter
 * Method:    native_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_media_ImageWriter_native_1close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
