/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_view_inputmethod_InputMethodManager */

#ifndef _Included_android_view_inputmethod_InputMethodManager
#define _Included_android_view_inputmethod_InputMethodManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_view_inputmethod_InputMethodManager
 * Method:    nativeInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_view_inputmethod_InputMethodManager_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     android_view_inputmethod_InputMethodManager
 * Method:    nativeUpdate
 * Signature: (Ljava/lang/String;IIIIZZ)V
 */
JNIEXPORT void JNICALL Java_android_view_inputmethod_InputMethodManager_nativeUpdate
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     android_view_inputmethod_InputMethodManager
 * Method:    nativeReset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_view_inputmethod_InputMethodManager_nativeReset
  (JNIEnv *, jclass);

/*
 * Class:     android_view_inputmethod_InputMethodManager
 * Method:    nativeShowSoftInput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_view_inputmethod_InputMethodManager_nativeShowSoftInput
  (JNIEnv *, jclass);

/*
 * Class:     android_view_inputmethod_InputMethodManager
 * Method:    nativeHideSoftInput
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_view_inputmethod_InputMethodManager_nativeHideSoftInput
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
