/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_view_Surface */

#ifndef _Included_android_view_Surface
#define _Included_android_view_Surface
#ifdef __cplusplus
extern "C" {
#endif
#undef android_view_Surface_ROTATION_0
#define android_view_Surface_ROTATION_0 0L
#undef android_view_Surface_ROTATION_180
#define android_view_Surface_ROTATION_180 2L
#undef android_view_Surface_ROTATION_270
#define android_view_Surface_ROTATION_270 3L
#undef android_view_Surface_ROTATION_90
#define android_view_Surface_ROTATION_90 1L
/*
 * Class:     android_view_Surface
 * Method:    native_releaseWindow
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_view_Surface_native_1releaseWindow
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
