/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_LightingColorFilter */

#ifndef _Included_android_graphics_LightingColorFilter
#define _Included_android_graphics_LightingColorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_LightingColorFilter
 * Method:    native_CreateLightingFilter
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_LightingColorFilter_native_1CreateLightingFilter
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
