/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_os_SystemProperties */

#ifndef _Included_android_os_SystemProperties
#define _Included_android_os_SystemProperties
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_os_SystemProperties
 * Method:    native_get
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_os_SystemProperties_native_1get
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
