/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_app_NativeActivity */

#ifndef _Included_android_app_NativeActivity
#define _Included_android_app_NativeActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef android_app_NativeActivity_MODE_PRIVATE
#define android_app_NativeActivity_MODE_PRIVATE 0L
#undef android_app_NativeActivity_CONTEXT_INCLUDE_CODE
#define android_app_NativeActivity_CONTEXT_INCLUDE_CODE 1L
#undef android_app_NativeActivity_CONTEXT_IGNORE_SECURITY
#define android_app_NativeActivity_CONTEXT_IGNORE_SECURITY 2L
#undef android_app_NativeActivity_CONTEXT_RESTRICTED
#define android_app_NativeActivity_CONTEXT_RESTRICTED 4L
#undef android_app_NativeActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define android_app_NativeActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef android_app_NativeActivity_MODE_NO_LOCALIZED_COLLATORS
#define android_app_NativeActivity_MODE_NO_LOCALIZED_COLLATORS 16L
#undef android_app_NativeActivity_BIND_AUTO_CREATE
#define android_app_NativeActivity_BIND_AUTO_CREATE 1L
#undef android_app_NativeActivity_BIND_IMPORTANT
#define android_app_NativeActivity_BIND_IMPORTANT 64L
#undef android_app_NativeActivity_BIND_WAIVE_PRIORITY
#define android_app_NativeActivity_BIND_WAIVE_PRIORITY 32L
#undef android_app_NativeActivity_RESULT_CANCELED
#define android_app_NativeActivity_RESULT_CANCELED 0L
#undef android_app_NativeActivity_RESULT_OK
#define android_app_NativeActivity_RESULT_OK -1L
#undef android_app_NativeActivity_LIFECYCLE_PRE
#define android_app_NativeActivity_LIFECYCLE_PRE 0L
#undef android_app_NativeActivity_LIFECYCLE_ON
#define android_app_NativeActivity_LIFECYCLE_ON 1L
#undef android_app_NativeActivity_LIFECYCLE_POST
#define android_app_NativeActivity_LIFECYCLE_POST 2L
#undef android_app_NativeActivity_LIFECYCLE_CREATE
#define android_app_NativeActivity_LIFECYCLE_CREATE 0L
#undef android_app_NativeActivity_LIFECYCLE_START
#define android_app_NativeActivity_LIFECYCLE_START 1L
#undef android_app_NativeActivity_LIFECYCLE_RESUME
#define android_app_NativeActivity_LIFECYCLE_RESUME 2L
#undef android_app_NativeActivity_LIFECYCLE_PAUSE
#define android_app_NativeActivity_LIFECYCLE_PAUSE 3L
#undef android_app_NativeActivity_LIFECYCLE_STOP
#define android_app_NativeActivity_LIFECYCLE_STOP 4L
#undef android_app_NativeActivity_LIFECYCLE_DESTROY
#define android_app_NativeActivity_LIFECYCLE_DESTROY 5L
#undef android_app_NativeActivity_LIFECYCLE_SAVE_INSTANCE_STATE
#define android_app_NativeActivity_LIFECYCLE_SAVE_INSTANCE_STATE 6L
/*
 * Class:     android_app_NativeActivity
 * Method:    loadNativeCode
 * Signature: (Ljava/lang/String;Ljava/lang/String;Landroid/os/MessageQueue;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILandroid/content/res/AssetManager;[B)J
 */
JNIEXPORT jlong JNICALL Java_android_app_NativeActivity_loadNativeCode
  (JNIEnv *, jobject, jstring, jstring, jobject, jstring, jstring, jstring, jint, jobject, jbyteArray);

/*
 * Class:     android_app_NativeActivity
 * Method:    unloadNativeCode
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_unloadNativeCode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_app_NativeActivity
 * Method:    onStartNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_onStartNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_app_NativeActivity
 * Method:    onResumeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_onResumeNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_app_NativeActivity
 * Method:    onSaveInstanceStateNative
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_android_app_NativeActivity_onSaveInstanceStateNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_app_NativeActivity
 * Method:    onPauseNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_onPauseNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_app_NativeActivity
 * Method:    onStopNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_onStopNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_app_NativeActivity
 * Method:    onConfigurationChangedNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_onConfigurationChangedNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_app_NativeActivity
 * Method:    onLowMemoryNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_onLowMemoryNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_app_NativeActivity
 * Method:    onWindowFocusChangedNative
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_onWindowFocusChangedNative
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     android_app_NativeActivity
 * Method:    onSurfaceCreatedNative
 * Signature: (JLandroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_onSurfaceCreatedNative
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     android_app_NativeActivity
 * Method:    onSurfaceChangedNative
 * Signature: (JLandroid/view/Surface;III)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_onSurfaceChangedNative
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint);

/*
 * Class:     android_app_NativeActivity
 * Method:    onSurfaceRedrawNeededNative
 * Signature: (JLandroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_onSurfaceRedrawNeededNative
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     android_app_NativeActivity
 * Method:    onSurfaceDestroyedNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_onSurfaceDestroyedNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_app_NativeActivity
 * Method:    onInputQueueCreatedNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_onInputQueueCreatedNative
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     android_app_NativeActivity
 * Method:    onInputQueueDestroyedNative
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_onInputQueueDestroyedNative
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     android_app_NativeActivity
 * Method:    onContentRectChangedNative
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_android_app_NativeActivity_onContentRectChangedNative
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
