/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Shader */

#ifndef _Included_android_graphics_Shader
#define _Included_android_graphics_Shader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_Shader
 * Method:    native_setLocalMatrix
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Shader_native_1setLocalMatrix
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
