/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_ColorMatrixColorFilter */

#ifndef _Included_android_graphics_ColorMatrixColorFilter
#define _Included_android_graphics_ColorMatrixColorFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_ColorMatrixColorFilter
 * Method:    native_CreateColorMatrixFilter
 * Signature: ([F)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_ColorMatrixColorFilter_native_1CreateColorMatrixFilter
  (JNIEnv *, jclass, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
