/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_text_TextRunShaper */

#ifndef _Included_android_graphics_text_TextRunShaper
#define _Included_android_graphics_text_TextRunShaper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_text_TextRunShaper
 * Method:    nativeShapeTextRun
 * Signature: ([CIIIIZJ)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_text_TextRunShaper_nativeShapeTextRun___3CIIIIZJ
  (JNIEnv *, jclass, jcharArray, jint, jint, jint, jint, jboolean, jlong);

/*
 * Class:     android_graphics_text_TextRunShaper
 * Method:    nativeShapeTextRun
 * Signature: (Ljava/lang/String;IIIIZJ)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_text_TextRunShaper_nativeShapeTextRun__Ljava_lang_String_2IIIIZJ
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
