/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_opengl_EGL14 */

#ifndef _Included_android_opengl_EGL14
#define _Included_android_opengl_EGL14
#ifdef __cplusplus
extern "C" {
#endif
#undef android_opengl_EGL14_EGL_DEFAULT_DISPLAY
#define android_opengl_EGL14_EGL_DEFAULT_DISPLAY 0L
#undef android_opengl_EGL14_EGL_FALSE
#define android_opengl_EGL14_EGL_FALSE 0L
#undef android_opengl_EGL14_EGL_TRUE
#define android_opengl_EGL14_EGL_TRUE 1L
#undef android_opengl_EGL14_EGL_ALPHA_SIZE
#define android_opengl_EGL14_EGL_ALPHA_SIZE 12321L
#undef android_opengl_EGL14_EGL_BAD_ACCESS
#define android_opengl_EGL14_EGL_BAD_ACCESS 12290L
#undef android_opengl_EGL14_EGL_BAD_ALLOC
#define android_opengl_EGL14_EGL_BAD_ALLOC 12291L
#undef android_opengl_EGL14_EGL_BAD_ATTRIBUTE
#define android_opengl_EGL14_EGL_BAD_ATTRIBUTE 12292L
#undef android_opengl_EGL14_EGL_BAD_CONFIG
#define android_opengl_EGL14_EGL_BAD_CONFIG 12293L
#undef android_opengl_EGL14_EGL_BAD_CONTEXT
#define android_opengl_EGL14_EGL_BAD_CONTEXT 12294L
#undef android_opengl_EGL14_EGL_BAD_CURRENT_SURFACE
#define android_opengl_EGL14_EGL_BAD_CURRENT_SURFACE 12295L
#undef android_opengl_EGL14_EGL_BAD_DISPLAY
#define android_opengl_EGL14_EGL_BAD_DISPLAY 12296L
#undef android_opengl_EGL14_EGL_BAD_MATCH
#define android_opengl_EGL14_EGL_BAD_MATCH 12297L
#undef android_opengl_EGL14_EGL_BAD_NATIVE_PIXMAP
#define android_opengl_EGL14_EGL_BAD_NATIVE_PIXMAP 12298L
#undef android_opengl_EGL14_EGL_BAD_NATIVE_WINDOW
#define android_opengl_EGL14_EGL_BAD_NATIVE_WINDOW 12299L
#undef android_opengl_EGL14_EGL_BAD_PARAMETER
#define android_opengl_EGL14_EGL_BAD_PARAMETER 12300L
#undef android_opengl_EGL14_EGL_BAD_SURFACE
#define android_opengl_EGL14_EGL_BAD_SURFACE 12301L
#undef android_opengl_EGL14_EGL_BLUE_SIZE
#define android_opengl_EGL14_EGL_BLUE_SIZE 12322L
#undef android_opengl_EGL14_EGL_BUFFER_DESTROYED
#define android_opengl_EGL14_EGL_BUFFER_DESTROYED 12437L
#undef android_opengl_EGL14_EGL_BUFFER_PRESERVED
#define android_opengl_EGL14_EGL_BUFFER_PRESERVED 12436L
#undef android_opengl_EGL14_EGL_BUFFER_SIZE
#define android_opengl_EGL14_EGL_BUFFER_SIZE 12320L
#undef android_opengl_EGL14_EGL_CLIENT_APIS
#define android_opengl_EGL14_EGL_CLIENT_APIS 12429L
#undef android_opengl_EGL14_EGL_COLOR_BUFFER_TYPE
#define android_opengl_EGL14_EGL_COLOR_BUFFER_TYPE 12351L
#undef android_opengl_EGL14_EGL_CONFIG_CAVEAT
#define android_opengl_EGL14_EGL_CONFIG_CAVEAT 12327L
#undef android_opengl_EGL14_EGL_CONFIG_ID
#define android_opengl_EGL14_EGL_CONFIG_ID 12328L
#undef android_opengl_EGL14_EGL_CONFORMANT
#define android_opengl_EGL14_EGL_CONFORMANT 12354L
#undef android_opengl_EGL14_EGL_CONTEXT_CLIENT_TYPE
#define android_opengl_EGL14_EGL_CONTEXT_CLIENT_TYPE 12439L
#undef android_opengl_EGL14_EGL_CONTEXT_CLIENT_VERSION
#define android_opengl_EGL14_EGL_CONTEXT_CLIENT_VERSION 12440L
#undef android_opengl_EGL14_EGL_CONTEXT_LOST
#define android_opengl_EGL14_EGL_CONTEXT_LOST 12302L
#undef android_opengl_EGL14_EGL_CORE_NATIVE_ENGINE
#define android_opengl_EGL14_EGL_CORE_NATIVE_ENGINE 12379L
#undef android_opengl_EGL14_EGL_DEPTH_SIZE
#define android_opengl_EGL14_EGL_DEPTH_SIZE 12325L
#undef android_opengl_EGL14_EGL_DONT_CARE
#define android_opengl_EGL14_EGL_DONT_CARE -1L
#undef android_opengl_EGL14_EGL_DRAW
#define android_opengl_EGL14_EGL_DRAW 12377L
#undef android_opengl_EGL14_EGL_EXTENSIONS
#define android_opengl_EGL14_EGL_EXTENSIONS 12373L
#undef android_opengl_EGL14_EGL_GREEN_SIZE
#define android_opengl_EGL14_EGL_GREEN_SIZE 12323L
#undef android_opengl_EGL14_EGL_HEIGHT
#define android_opengl_EGL14_EGL_HEIGHT 12374L
#undef android_opengl_EGL14_EGL_HORIZONTAL_RESOLUTION
#define android_opengl_EGL14_EGL_HORIZONTAL_RESOLUTION 12432L
#undef android_opengl_EGL14_EGL_LARGEST_PBUFFER
#define android_opengl_EGL14_EGL_LARGEST_PBUFFER 12376L
#undef android_opengl_EGL14_EGL_LEVEL
#define android_opengl_EGL14_EGL_LEVEL 12329L
#undef android_opengl_EGL14_EGL_LUMINANCE_BUFFER
#define android_opengl_EGL14_EGL_LUMINANCE_BUFFER 12431L
#undef android_opengl_EGL14_EGL_LUMINANCE_SIZE
#define android_opengl_EGL14_EGL_LUMINANCE_SIZE 12349L
#undef android_opengl_EGL14_EGL_MATCH_NATIVE_PIXMAP
#define android_opengl_EGL14_EGL_MATCH_NATIVE_PIXMAP 12353L
#undef android_opengl_EGL14_EGL_MAX_PBUFFER_HEIGHT
#define android_opengl_EGL14_EGL_MAX_PBUFFER_HEIGHT 12330L
#undef android_opengl_EGL14_EGL_MAX_PBUFFER_PIXELS
#define android_opengl_EGL14_EGL_MAX_PBUFFER_PIXELS 12331L
#undef android_opengl_EGL14_EGL_MAX_PBUFFER_WIDTH
#define android_opengl_EGL14_EGL_MAX_PBUFFER_WIDTH 12332L
#undef android_opengl_EGL14_EGL_MAX_SWAP_INTERVAL
#define android_opengl_EGL14_EGL_MAX_SWAP_INTERVAL 12348L
#undef android_opengl_EGL14_EGL_MIN_SWAP_INTERVAL
#define android_opengl_EGL14_EGL_MIN_SWAP_INTERVAL 12347L
#undef android_opengl_EGL14_EGL_MIPMAP_LEVEL
#define android_opengl_EGL14_EGL_MIPMAP_LEVEL 12419L
#undef android_opengl_EGL14_EGL_MIPMAP_TEXTURE
#define android_opengl_EGL14_EGL_MIPMAP_TEXTURE 12418L
#undef android_opengl_EGL14_EGL_MULTISAMPLE_RESOLVE
#define android_opengl_EGL14_EGL_MULTISAMPLE_RESOLVE 12441L
#undef android_opengl_EGL14_EGL_MULTISAMPLE_RESOLVE_BOX
#define android_opengl_EGL14_EGL_MULTISAMPLE_RESOLVE_BOX 12443L
#undef android_opengl_EGL14_EGL_MULTISAMPLE_RESOLVE_BOX_BIT
#define android_opengl_EGL14_EGL_MULTISAMPLE_RESOLVE_BOX_BIT 512L
#undef android_opengl_EGL14_EGL_MULTISAMPLE_RESOLVE_DEFAULT
#define android_opengl_EGL14_EGL_MULTISAMPLE_RESOLVE_DEFAULT 12442L
#undef android_opengl_EGL14_EGL_NATIVE_RENDERABLE
#define android_opengl_EGL14_EGL_NATIVE_RENDERABLE 12333L
#undef android_opengl_EGL14_EGL_NATIVE_VISUAL_ID
#define android_opengl_EGL14_EGL_NATIVE_VISUAL_ID 12334L
#undef android_opengl_EGL14_EGL_NATIVE_VISUAL_TYPE
#define android_opengl_EGL14_EGL_NATIVE_VISUAL_TYPE 12335L
#undef android_opengl_EGL14_EGL_NONE
#define android_opengl_EGL14_EGL_NONE 12344L
#undef android_opengl_EGL14_EGL_NON_CONFORMANT_CONFIG
#define android_opengl_EGL14_EGL_NON_CONFORMANT_CONFIG 12369L
#undef android_opengl_EGL14_EGL_NOT_INITIALIZED
#define android_opengl_EGL14_EGL_NOT_INITIALIZED 12289L
#undef android_opengl_EGL14_EGL_NO_TEXTURE
#define android_opengl_EGL14_EGL_NO_TEXTURE 12380L
#undef android_opengl_EGL14_EGL_OPENGL_API
#define android_opengl_EGL14_EGL_OPENGL_API 12450L
#undef android_opengl_EGL14_EGL_OPENGL_BIT
#define android_opengl_EGL14_EGL_OPENGL_BIT 8L
#undef android_opengl_EGL14_EGL_OPENGL_ES2_BIT
#define android_opengl_EGL14_EGL_OPENGL_ES2_BIT 4L
#undef android_opengl_EGL14_EGL_OPENGL_ES_API
#define android_opengl_EGL14_EGL_OPENGL_ES_API 12448L
#undef android_opengl_EGL14_EGL_OPENGL_ES_BIT
#define android_opengl_EGL14_EGL_OPENGL_ES_BIT 1L
#undef android_opengl_EGL14_EGL_OPENVG_API
#define android_opengl_EGL14_EGL_OPENVG_API 12449L
#undef android_opengl_EGL14_EGL_OPENVG_BIT
#define android_opengl_EGL14_EGL_OPENVG_BIT 2L
#undef android_opengl_EGL14_EGL_OPENVG_IMAGE
#define android_opengl_EGL14_EGL_OPENVG_IMAGE 12438L
#undef android_opengl_EGL14_EGL_PBUFFER_BIT
#define android_opengl_EGL14_EGL_PBUFFER_BIT 1L
#undef android_opengl_EGL14_EGL_PIXEL_ASPECT_RATIO
#define android_opengl_EGL14_EGL_PIXEL_ASPECT_RATIO 12434L
#undef android_opengl_EGL14_EGL_PIXMAP_BIT
#define android_opengl_EGL14_EGL_PIXMAP_BIT 2L
#undef android_opengl_EGL14_EGL_READ
#define android_opengl_EGL14_EGL_READ 12378L
#undef android_opengl_EGL14_EGL_RED_SIZE
#define android_opengl_EGL14_EGL_RED_SIZE 12324L
#undef android_opengl_EGL14_EGL_RENDERABLE_TYPE
#define android_opengl_EGL14_EGL_RENDERABLE_TYPE 12352L
#undef android_opengl_EGL14_EGL_RENDER_BUFFER
#define android_opengl_EGL14_EGL_RENDER_BUFFER 12422L
#undef android_opengl_EGL14_EGL_RGB_BUFFER
#define android_opengl_EGL14_EGL_RGB_BUFFER 12430L
#undef android_opengl_EGL14_EGL_SAMPLES
#define android_opengl_EGL14_EGL_SAMPLES 12337L
#undef android_opengl_EGL14_EGL_SAMPLE_BUFFERS
#define android_opengl_EGL14_EGL_SAMPLE_BUFFERS 12338L
#undef android_opengl_EGL14_EGL_SINGLE_BUFFER
#define android_opengl_EGL14_EGL_SINGLE_BUFFER 12421L
#undef android_opengl_EGL14_EGL_SLOW_CONFIG
#define android_opengl_EGL14_EGL_SLOW_CONFIG 12368L
#undef android_opengl_EGL14_EGL_STENCIL_SIZE
#define android_opengl_EGL14_EGL_STENCIL_SIZE 12326L
#undef android_opengl_EGL14_EGL_SUCCESS
#define android_opengl_EGL14_EGL_SUCCESS 12288L
#undef android_opengl_EGL14_EGL_SURFACE_TYPE
#define android_opengl_EGL14_EGL_SURFACE_TYPE 12339L
#undef android_opengl_EGL14_EGL_SWAP_BEHAVIOR
#define android_opengl_EGL14_EGL_SWAP_BEHAVIOR 12435L
#undef android_opengl_EGL14_EGL_TEXTURE_2D
#define android_opengl_EGL14_EGL_TEXTURE_2D 12383L
#undef android_opengl_EGL14_EGL_TEXTURE_FORMAT
#define android_opengl_EGL14_EGL_TEXTURE_FORMAT 12416L
#undef android_opengl_EGL14_EGL_TEXTURE_RGB
#define android_opengl_EGL14_EGL_TEXTURE_RGB 12381L
#undef android_opengl_EGL14_EGL_TEXTURE_RGBA
#define android_opengl_EGL14_EGL_TEXTURE_RGBA 12382L
#undef android_opengl_EGL14_EGL_TEXTURE_TARGET
#define android_opengl_EGL14_EGL_TEXTURE_TARGET 12417L
#undef android_opengl_EGL14_EGL_TRANSPARENT_BLUE_VALUE
#define android_opengl_EGL14_EGL_TRANSPARENT_BLUE_VALUE 12341L
#undef android_opengl_EGL14_EGL_TRANSPARENT_GREEN_VALUE
#define android_opengl_EGL14_EGL_TRANSPARENT_GREEN_VALUE 12342L
#undef android_opengl_EGL14_EGL_TRANSPARENT_RED_VALUE
#define android_opengl_EGL14_EGL_TRANSPARENT_RED_VALUE 12343L
#undef android_opengl_EGL14_EGL_TRANSPARENT_RGB
#define android_opengl_EGL14_EGL_TRANSPARENT_RGB 12370L
#undef android_opengl_EGL14_EGL_TRANSPARENT_TYPE
#define android_opengl_EGL14_EGL_TRANSPARENT_TYPE 12340L
#undef android_opengl_EGL14_EGL_VENDOR
#define android_opengl_EGL14_EGL_VENDOR 12371L
#undef android_opengl_EGL14_EGL_VERSION
#define android_opengl_EGL14_EGL_VERSION 12372L
#undef android_opengl_EGL14_EGL_VERTICAL_RESOLUTION
#define android_opengl_EGL14_EGL_VERTICAL_RESOLUTION 12433L
#undef android_opengl_EGL14_EGL_WIDTH
#define android_opengl_EGL14_EGL_WIDTH 12375L
#undef android_opengl_EGL14_EGL_WINDOW_BIT
#define android_opengl_EGL14_EGL_WINDOW_BIT 4L
/*
 * Class:     android_opengl_EGL14
 * Method:    eglGetError
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_opengl_EGL14_eglGetError
  (JNIEnv *, jclass);

/*
 * Class:     android_opengl_EGL14
 * Method:    eglBindAPI
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_eglBindAPI
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_EGL14
 * Method:    eglQueryAPI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_opengl_EGL14_eglQueryAPI
  (JNIEnv *, jclass);

/*
 * Class:     android_opengl_EGL14
 * Method:    eglWaitClient
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_eglWaitClient
  (JNIEnv *, jclass);

/*
 * Class:     android_opengl_EGL14
 * Method:    eglWaitGL
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_eglWaitGL
  (JNIEnv *, jclass);

/*
 * Class:     android_opengl_EGL14
 * Method:    eglWaitNative
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_eglWaitNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_EGL14
 * Method:    eglReleaseThread
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_eglReleaseThread
  (JNIEnv *, jclass);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglGetDisplay
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_android_opengl_EGL14_native_1eglGetDisplay
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglInitialize
 * Signature: (J[I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_native_1eglInitialize
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglTerminate
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_native_1eglTerminate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglQueryString
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_opengl_EGL14_native_1eglQueryString
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglChooseConfig
 * Signature: (J[I[JI[I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_native_1eglChooseConfig
  (JNIEnv *, jclass, jlong, jintArray, jlongArray, jint, jintArray);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglGetConfigAttrib
 * Signature: (JJI[I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_native_1eglGetConfigAttrib
  (JNIEnv *, jclass, jlong, jlong, jint, jintArray);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglCreateContext
 * Signature: (JJJ[I)J
 */
JNIEXPORT jlong JNICALL Java_android_opengl_EGL14_native_1eglCreateContext
  (JNIEnv *, jclass, jlong, jlong, jlong, jintArray);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglDestroyContext
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_native_1eglDestroyContext
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglCreateWindowSurface
 * Signature: (JJLandroid/view/Surface;[I)J
 */
JNIEXPORT jlong JNICALL Java_android_opengl_EGL14_native_1eglCreateWindowSurface
  (JNIEnv *, jclass, jlong, jlong, jobject, jintArray);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglCreateWindowSurfaceTexture
 * Signature: (JJLandroid/graphics/SurfaceTexture;[I)J
 */
JNIEXPORT jlong JNICALL Java_android_opengl_EGL14_native_1eglCreateWindowSurfaceTexture
  (JNIEnv *, jclass, jlong, jlong, jobject, jintArray);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglCreatePbufferSurface
 * Signature: (JJ[I)J
 */
JNIEXPORT jlong JNICALL Java_android_opengl_EGL14_native_1eglCreatePbufferSurface
  (JNIEnv *, jclass, jlong, jlong, jintArray);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglDestroySurface
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_native_1eglDestroySurface
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglQuerySurface
 * Signature: (JJI[I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_native_1eglQuerySurface
  (JNIEnv *, jclass, jlong, jlong, jint, jintArray);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglSurfaceAttrib
 * Signature: (JJII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_native_1eglSurfaceAttrib
  (JNIEnv *, jclass, jlong, jlong, jint, jint);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglQueryContext
 * Signature: (JJI[I)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_native_1eglQueryContext
  (JNIEnv *, jclass, jlong, jlong, jint, jintArray);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglMakeCurrent
 * Signature: (JJJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_native_1eglMakeCurrent
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglSwapBuffers
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_native_1eglSwapBuffers
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglSwapInterval
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL14_native_1eglSwapInterval
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglGetCurrentDisplay
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_opengl_EGL14_native_1eglGetCurrentDisplay
  (JNIEnv *, jclass);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglGetCurrentContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_opengl_EGL14_native_1eglGetCurrentContext
  (JNIEnv *, jclass);

/*
 * Class:     android_opengl_EGL14
 * Method:    native_eglGetCurrentSurface
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_android_opengl_EGL14_native_1eglGetCurrentSurface
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
