/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_atl_ATLContentHub */

#ifndef _Included_android_atl_ATLContentHub
#define _Included_android_atl_ATLContentHub
#ifdef __cplusplus
extern "C" {
#endif
#undef android_atl_ATLContentHub_SELECT_SINGLE
#define android_atl_ATLContentHub_SELECT_SINGLE 0L
#undef android_atl_ATLContentHub_SELECT_MULTIPLE
#define android_atl_ATLContentHub_SELECT_MULTIPLE 1L
/*
 * Class:     android_atl_ATLContentHub
 * Method:    nativeListSources
 * Signature: (Ljava/lang/String;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_android_atl_ATLContentHub_nativeListSources
  (JNIEnv *, jclass, jstring);

/*
 * Class:     android_atl_ATLContentHub
 * Method:    nativeRenderSvg
 * Signature: ([BI)[I
 */
JNIEXPORT jintArray JNICALL Java_android_atl_ATLContentHub_nativeRenderSvg
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     android_atl_ATLContentHub
 * Method:    nativeImport
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_android_atl_ATLContentHub_nativeImport
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     android_atl_ATLContentHub
 * Method:    nativeImportCancel
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_atl_ATLContentHub_nativeImportCancel
  (JNIEnv *, jclass);

/*
 * Class:     android_atl_ATLContentHub
 * Method:    nativeClearTemp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_atl_ATLContentHub_nativeClearTemp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
