/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_hardware_camera2_impl_CameraDeviceNative */

#ifndef _Included_android_hardware_camera2_impl_CameraDeviceNative
#define _Included_android_hardware_camera2_impl_CameraDeviceNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_hardware_camera2_impl_CameraDeviceNative
 * Method:    native_open
 * Signature: (Ljava/lang/String;Landroid/hardware/camera2/impl/CameraDeviceNative;)J
 */
JNIEXPORT jlong JNICALL Java_android_hardware_camera2_impl_CameraDeviceNative_native_1open
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     android_hardware_camera2_impl_CameraDeviceNative
 * Method:    native_configure
 * Signature: (J[Landroid/view/Surface;[Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_android_hardware_camera2_impl_CameraDeviceNative_native_1configure
  (JNIEnv *, jclass, jlong, jobjectArray, jobjectArray);

/*
 * Class:     android_hardware_camera2_impl_CameraDeviceNative
 * Method:    native_setRepeatingRequest
 * Signature: (JIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_android_hardware_camera2_impl_CameraDeviceNative_native_1setRepeatingRequest
  (JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     android_hardware_camera2_impl_CameraDeviceNative
 * Method:    native_capture
 * Signature: (JIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_android_hardware_camera2_impl_CameraDeviceNative_native_1capture
  (JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     android_hardware_camera2_impl_CameraDeviceNative
 * Method:    native_createInputSurface
 * Signature: (JLandroid/view/Surface;IIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_hardware_camera2_impl_CameraDeviceNative_native_1createInputSurface
  (JNIEnv *, jclass, jlong, jobject, jint, jint, jint, jboolean);

/*
 * Class:     android_hardware_camera2_impl_CameraDeviceNative
 * Method:    native_clearInputSurface
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_hardware_camera2_impl_CameraDeviceNative_native_1clearInputSurface
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_hardware_camera2_impl_CameraDeviceNative
 * Method:    native_reprocess
 * Signature: (JIJI)Z
 */
JNIEXPORT jboolean JNICALL Java_android_hardware_camera2_impl_CameraDeviceNative_native_1reprocess
  (JNIEnv *, jclass, jlong, jint, jlong, jint);

/*
 * Class:     android_hardware_camera2_impl_CameraDeviceNative
 * Method:    native_stopRepeating
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_hardware_camera2_impl_CameraDeviceNative_native_1stopRepeating
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_hardware_camera2_impl_CameraDeviceNative
 * Method:    native_abortCaptures
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_android_hardware_camera2_impl_CameraDeviceNative_native_1abortCaptures
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_hardware_camera2_impl_CameraDeviceNative
 * Method:    native_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_hardware_camera2_impl_CameraDeviceNative_native_1close
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
