/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_opengl_EGL15 */

#ifndef _Included_android_opengl_EGL15
#define _Included_android_opengl_EGL15
#ifdef __cplusplus
extern "C" {
#endif
#undef android_opengl_EGL15_EGL_CONTEXT_MAJOR_VERSION
#define android_opengl_EGL15_EGL_CONTEXT_MAJOR_VERSION 12440L
#undef android_opengl_EGL15_EGL_CONTEXT_MINOR_VERSION
#define android_opengl_EGL15_EGL_CONTEXT_MINOR_VERSION 12539L
#undef android_opengl_EGL15_EGL_CONTEXT_OPENGL_PROFILE_MASK
#define android_opengl_EGL15_EGL_CONTEXT_OPENGL_PROFILE_MASK 12541L
#undef android_opengl_EGL15_EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT
#define android_opengl_EGL15_EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT 1L
#undef android_opengl_EGL15_EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT
#define android_opengl_EGL15_EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT 2L
#undef android_opengl_EGL15_EGL_CONTEXT_OPENGL_DEBUG
#define android_opengl_EGL15_EGL_CONTEXT_OPENGL_DEBUG 12720L
#undef android_opengl_EGL15_EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE
#define android_opengl_EGL15_EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE 12721L
#undef android_opengl_EGL15_EGL_CONTEXT_OPENGL_ROBUST_ACCESS
#define android_opengl_EGL15_EGL_CONTEXT_OPENGL_ROBUST_ACCESS 12722L
#undef android_opengl_EGL15_EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY
#define android_opengl_EGL15_EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY 12733L
#undef android_opengl_EGL15_EGL_NO_RESET_NOTIFICATION
#define android_opengl_EGL15_EGL_NO_RESET_NOTIFICATION 12734L
#undef android_opengl_EGL15_EGL_LOSE_CONTEXT_ON_RESET
#define android_opengl_EGL15_EGL_LOSE_CONTEXT_ON_RESET 12735L
#undef android_opengl_EGL15_EGL_OPENGL_ES3_BIT
#define android_opengl_EGL15_EGL_OPENGL_ES3_BIT 64L
#undef android_opengl_EGL15_EGL_SYNC_FENCE
#define android_opengl_EGL15_EGL_SYNC_FENCE 12537L
#undef android_opengl_EGL15_EGL_SYNC_TYPE
#define android_opengl_EGL15_EGL_SYNC_TYPE 12535L
#undef android_opengl_EGL15_EGL_SYNC_STATUS
#define android_opengl_EGL15_EGL_SYNC_STATUS 12529L
#undef android_opengl_EGL15_EGL_SYNC_CONDITION
#define android_opengl_EGL15_EGL_SYNC_CONDITION 12536L
#undef android_opengl_EGL15_EGL_SIGNALED
#define android_opengl_EGL15_EGL_SIGNALED 12530L
#undef android_opengl_EGL15_EGL_UNSIGNALED
#define android_opengl_EGL15_EGL_UNSIGNALED 12531L
#undef android_opengl_EGL15_EGL_SYNC_FLUSH_COMMANDS_BIT
#define android_opengl_EGL15_EGL_SYNC_FLUSH_COMMANDS_BIT 1L
#undef android_opengl_EGL15_EGL_FOREVER
#define android_opengl_EGL15_EGL_FOREVER -1LL
#undef android_opengl_EGL15_EGL_TIMEOUT_EXPIRED
#define android_opengl_EGL15_EGL_TIMEOUT_EXPIRED 12533L
#undef android_opengl_EGL15_EGL_CONDITION_SATISFIED
#define android_opengl_EGL15_EGL_CONDITION_SATISFIED 12534L
#undef android_opengl_EGL15_EGL_SYNC_PRIOR_COMMANDS_COMPLETE
#define android_opengl_EGL15_EGL_SYNC_PRIOR_COMMANDS_COMPLETE 12528L
#undef android_opengl_EGL15_EGL_SYNC_CL_EVENT
#define android_opengl_EGL15_EGL_SYNC_CL_EVENT 12542L
#undef android_opengl_EGL15_EGL_SYNC_CL_EVENT_COMPLETE
#define android_opengl_EGL15_EGL_SYNC_CL_EVENT_COMPLETE 12543L
#undef android_opengl_EGL15_EGL_CL_EVENT_HANDLE
#define android_opengl_EGL15_EGL_CL_EVENT_HANDLE 12444L
#undef android_opengl_EGL15_EGL_GL_COLORSPACE
#define android_opengl_EGL15_EGL_GL_COLORSPACE 12445L
#undef android_opengl_EGL15_EGL_GL_COLORSPACE_SRGB
#define android_opengl_EGL15_EGL_GL_COLORSPACE_SRGB 12425L
#undef android_opengl_EGL15_EGL_GL_COLORSPACE_LINEAR
#define android_opengl_EGL15_EGL_GL_COLORSPACE_LINEAR 12426L
#undef android_opengl_EGL15_EGL_GL_RENDERBUFFER
#define android_opengl_EGL15_EGL_GL_RENDERBUFFER 12473L
#undef android_opengl_EGL15_EGL_GL_TEXTURE_2D
#define android_opengl_EGL15_EGL_GL_TEXTURE_2D 12465L
#undef android_opengl_EGL15_EGL_GL_TEXTURE_LEVEL
#define android_opengl_EGL15_EGL_GL_TEXTURE_LEVEL 12476L
#undef android_opengl_EGL15_EGL_IMAGE_PRESERVED
#define android_opengl_EGL15_EGL_IMAGE_PRESERVED 12498L
/*
 * Class:     android_opengl_EGL15
 * Method:    native_eglCreateSync
 * Signature: (JI[J)J
 */
JNIEXPORT jlong JNICALL Java_android_opengl_EGL15_native_1eglCreateSync
  (JNIEnv *, jclass, jlong, jint, jlongArray);

/*
 * Class:     android_opengl_EGL15
 * Method:    native_eglDestroySync
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL15_native_1eglDestroySync
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_opengl_EGL15
 * Method:    native_eglClientWaitSync
 * Signature: (JJIJ)I
 */
JNIEXPORT jint JNICALL Java_android_opengl_EGL15_native_1eglClientWaitSync
  (JNIEnv *, jclass, jlong, jlong, jint, jlong);

/*
 * Class:     android_opengl_EGL15
 * Method:    native_eglWaitSync
 * Signature: (JJI)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL15_native_1eglWaitSync
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     android_opengl_EGL15
 * Method:    native_eglGetSyncAttrib
 * Signature: (JJI[J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGL15_native_1eglGetSyncAttrib
  (JNIEnv *, jclass, jlong, jlong, jint, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
