/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_text_LineBreaker */

#ifndef _Included_android_graphics_text_LineBreaker
#define _Included_android_graphics_text_LineBreaker
#ifdef __cplusplus
extern "C" {
#endif
#undef android_graphics_text_LineBreaker_BREAK_STRATEGY_SIMPLE
#define android_graphics_text_LineBreaker_BREAK_STRATEGY_SIMPLE 0L
#undef android_graphics_text_LineBreaker_BREAK_STRATEGY_HIGH_QUALITY
#define android_graphics_text_LineBreaker_BREAK_STRATEGY_HIGH_QUALITY 1L
#undef android_graphics_text_LineBreaker_BREAK_STRATEGY_BALANCED
#define android_graphics_text_LineBreaker_BREAK_STRATEGY_BALANCED 2L
#undef android_graphics_text_LineBreaker_HYPHENATION_FREQUENCY_NONE
#define android_graphics_text_LineBreaker_HYPHENATION_FREQUENCY_NONE 0L
#undef android_graphics_text_LineBreaker_HYPHENATION_FREQUENCY_NORMAL
#define android_graphics_text_LineBreaker_HYPHENATION_FREQUENCY_NORMAL 1L
#undef android_graphics_text_LineBreaker_HYPHENATION_FREQUENCY_FULL
#define android_graphics_text_LineBreaker_HYPHENATION_FREQUENCY_FULL 2L
#undef android_graphics_text_LineBreaker_JUSTIFICATION_MODE_NONE
#define android_graphics_text_LineBreaker_JUSTIFICATION_MODE_NONE 0L
#undef android_graphics_text_LineBreaker_JUSTIFICATION_MODE_INTER_WORD
#define android_graphics_text_LineBreaker_JUSTIFICATION_MODE_INTER_WORD 1L
/*
 * Class:     android_graphics_text_LineBreaker
 * Method:    nInit
 * Signature: (IIZ[I)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_text_LineBreaker_nInit
  (JNIEnv *, jclass, jint, jint, jboolean, jintArray);

/*
 * Class:     android_graphics_text_LineBreaker
 * Method:    nGetReleaseFunc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_text_LineBreaker_nGetReleaseFunc
  (JNIEnv *, jclass);

/*
 * Class:     android_graphics_text_LineBreaker
 * Method:    nComputeLineBreaks
 * Signature: (J[CJIFIF[FFI)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_text_LineBreaker_nComputeLineBreaks
  (JNIEnv *, jclass, jlong, jcharArray, jlong, jint, jfloat, jint, jfloat, jfloatArray, jfloat, jint);

/*
 * Class:     android_graphics_text_LineBreaker
 * Method:    nGetLineCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_text_LineBreaker_nGetLineCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_text_LineBreaker
 * Method:    nGetLineBreakOffset
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_text_LineBreaker_nGetLineBreakOffset
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_text_LineBreaker
 * Method:    nGetLineWidth
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_android_graphics_text_LineBreaker_nGetLineWidth
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_text_LineBreaker
 * Method:    nGetLineAscent
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_android_graphics_text_LineBreaker_nGetLineAscent
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_text_LineBreaker
 * Method:    nGetLineDescent
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_android_graphics_text_LineBreaker_nGetLineDescent
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_text_LineBreaker
 * Method:    nGetLineFlag
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_text_LineBreaker_nGetLineFlag
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_text_LineBreaker
 * Method:    nGetReleaseResultFunc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_text_LineBreaker_nGetReleaseResultFunc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
