/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_ComposeShader */

#ifndef _Included_android_graphics_ComposeShader
#define _Included_android_graphics_ComposeShader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_ComposeShader
 * Method:    native_create
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_ComposeShader_native_1create
  (JNIEnv *, jclass, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
