/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_LinearGradient */

#ifndef _Included_android_graphics_LinearGradient
#define _Included_android_graphics_LinearGradient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_LinearGradient
 * Method:    native_create
 * Signature: (FFFF[I[FI)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_LinearGradient_native_1create
  (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jintArray, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
