/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_hardware_camera2_impl_CameraMetadataNative */

#ifndef _Included_android_hardware_camera2_impl_CameraMetadataNative
#define _Included_android_hardware_camera2_impl_CameraMetadataNative
#ifdef __cplusplus
extern "C" {
#endif
#undef android_hardware_camera2_impl_CameraMetadataNative_KEYS_CHARACTERISTICS
#define android_hardware_camera2_impl_CameraMetadataNative_KEYS_CHARACTERISTICS 0L
#undef android_hardware_camera2_impl_CameraMetadataNative_KEYS_REQUEST
#define android_hardware_camera2_impl_CameraMetadataNative_KEYS_REQUEST 1L
#undef android_hardware_camera2_impl_CameraMetadataNative_KEYS_RESULT
#define android_hardware_camera2_impl_CameraMetadataNative_KEYS_RESULT 2L
#undef android_hardware_camera2_impl_CameraMetadataNative_TYPE_BYTE
#define android_hardware_camera2_impl_CameraMetadataNative_TYPE_BYTE 0L
#undef android_hardware_camera2_impl_CameraMetadataNative_TYPE_INT32
#define android_hardware_camera2_impl_CameraMetadataNative_TYPE_INT32 1L
#undef android_hardware_camera2_impl_CameraMetadataNative_TYPE_FLOAT
#define android_hardware_camera2_impl_CameraMetadataNative_TYPE_FLOAT 2L
#undef android_hardware_camera2_impl_CameraMetadataNative_TYPE_INT64
#define android_hardware_camera2_impl_CameraMetadataNative_TYPE_INT64 3L
#undef android_hardware_camera2_impl_CameraMetadataNative_TYPE_DOUBLE
#define android_hardware_camera2_impl_CameraMetadataNative_TYPE_DOUBLE 4L
#undef android_hardware_camera2_impl_CameraMetadataNative_TYPE_RATIONAL
#define android_hardware_camera2_impl_CameraMetadataNative_TYPE_RATIONAL 5L
#undef android_hardware_camera2_impl_CameraMetadataNative_TAG_INVALID
#define android_hardware_camera2_impl_CameraMetadataNative_TAG_INVALID -1L
/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_getCameraIdList
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1getCameraIdList
  (JNIEnv *, jclass);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_getStaticMetadata
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1getStaticMetadata
  (JNIEnv *, jclass, jstring);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_getAvailableKeys
 * Signature: (Ljava/lang/String;I)[I
 */
JNIEXPORT jintArray JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1getAvailableKeys
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1create
  (JNIEnv *, jclass);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_copy
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1copy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_erase
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1erase
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_writeLongs
 * Signature: (JI[J)V
 */
JNIEXPORT void JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1writeLongs
  (JNIEnv *, jclass, jlong, jint, jlongArray);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_writeDoubles
 * Signature: (JI[D)V
 */
JNIEXPORT void JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1writeDoubles
  (JNIEnv *, jclass, jlong, jint, jdoubleArray);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_writeBytes
 * Signature: (JI[B)V
 */
JNIEXPORT void JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1writeBytes
  (JNIEnv *, jclass, jlong, jint, jbyteArray);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_getTags
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1getTags
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_getTag
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1getTag
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_getTagName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1getTagName
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_getType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1getType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_readBytes
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1readBytes
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_readInts
 * Signature: (JI)[I
 */
JNIEXPORT jintArray JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1readInts
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_readFloats
 * Signature: (JI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1readFloats
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_readLongs
 * Signature: (JI)[J
 */
JNIEXPORT jlongArray JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1readLongs
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_hardware_camera2_impl_CameraMetadataNative
 * Method:    native_readDoubles
 * Signature: (JI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_android_hardware_camera2_impl_CameraMetadataNative_native_1readDoubles
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
