/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_view_ViewRootImpl */

#ifndef _Included_android_view_ViewRootImpl
#define _Included_android_view_ViewRootImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_view_ViewRootImpl
 * Method:    nativeInvalidate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_view_ViewRootImpl_nativeInvalidate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_view_ViewRootImpl
 * Method:    nativeRequestLayout
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_view_ViewRootImpl_nativeRequestLayout
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
