/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_text_PositionedGlyphs */

#ifndef _Included_android_graphics_text_PositionedGlyphs
#define _Included_android_graphics_text_PositionedGlyphs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_text_PositionedGlyphs
 * Method:    nGetGlyphCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_text_PositionedGlyphs_nGetGlyphCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_text_PositionedGlyphs
 * Method:    nGetTotalAdvance
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_android_graphics_text_PositionedGlyphs_nGetTotalAdvance
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_text_PositionedGlyphs
 * Method:    nGetAscent
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_android_graphics_text_PositionedGlyphs_nGetAscent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_text_PositionedGlyphs
 * Method:    nGetDescent
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_android_graphics_text_PositionedGlyphs_nGetDescent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_text_PositionedGlyphs
 * Method:    nGetGlyphId
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_text_PositionedGlyphs_nGetGlyphId
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_text_PositionedGlyphs
 * Method:    nGetX
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_android_graphics_text_PositionedGlyphs_nGetX
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_text_PositionedGlyphs
 * Method:    nGetY
 * Signature: (JI)F
 */
JNIEXPORT jfloat JNICALL Java_android_graphics_text_PositionedGlyphs_nGetY
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_text_PositionedGlyphs
 * Method:    nGetFont
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_text_PositionedGlyphs_nGetFont
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_text_PositionedGlyphs
 * Method:    nReleaseFunc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_text_PositionedGlyphs_nReleaseFunc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
