/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_media_ImageReader */

#ifndef _Included_android_media_ImageReader
#define _Included_android_media_ImageReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_media_ImageReader
 * Method:    native_create
 * Signature: (IIIIJLandroid/media/ImageReader;)J
 */
JNIEXPORT jlong JNICALL Java_android_media_ImageReader_native_1create
  (JNIEnv *, jclass, jint, jint, jint, jint, jlong, jobject);

/*
 * Class:     android_media_ImageReader
 * Method:    native_attachSurface
 * Signature: (JLandroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_android_media_ImageReader_native_1attachSurface
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     android_media_ImageReader
 * Method:    native_setListenerEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_android_media_ImageReader_native_1setListenerEnabled
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     android_media_ImageReader
 * Method:    native_hasQueuedImage
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_android_media_ImageReader_native_1hasQueuedImage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_ImageReader
 * Method:    native_acquire
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_android_media_ImageReader_native_1acquire
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     android_media_ImageReader
 * Method:    native_discardFreeBuffers
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_media_ImageReader_native_1discardFreeBuffers
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_ImageReader
 * Method:    native_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_media_ImageReader_native_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_ImageReader
 * Method:    native_imageInfo
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_android_media_ImageReader_native_1imageInfo
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_ImageReader
 * Method:    native_planeStrides
 * Signature: (JI)[I
 */
JNIEXPORT jintArray JNICALL Java_android_media_ImageReader_native_1planeStrides
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_media_ImageReader
 * Method:    native_planeBuffer
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_android_media_ImageReader_native_1planeBuffer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_media_ImageReader
 * Method:    native_imageHardwareBuffer
 * Signature: (J)Landroid/hardware/HardwareBuffer;
 */
JNIEXPORT jobject JNICALL Java_android_media_ImageReader_native_1imageHardwareBuffer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_media_ImageReader
 * Method:    native_imageClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_media_ImageReader_native_1imageClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
