/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_Bitmap */

#ifndef _Included_android_graphics_Bitmap
#define _Included_android_graphics_Bitmap
#ifdef __cplusplus
extern "C" {
#endif
#undef android_graphics_Bitmap_DENSITY_NONE
#define android_graphics_Bitmap_DENSITY_NONE 0L
/*
 * Class:     android_graphics_Bitmap
 * Method:    native_create_bitmap
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Bitmap_native_1create_1bitmap
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_create_canvas
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Bitmap_native_1create_1canvas
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_create_gdk_texture
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Bitmap_native_1create_1gdk_1texture
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_unref_gdk_texture
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Bitmap_native_1unref_1gdk_1texture
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_get_width
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Bitmap_native_1get_1width
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_get_height
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_android_graphics_Bitmap_native_1get_1height
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_erase_color
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Bitmap_native_1erase_1color
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_recycle
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Bitmap_native_1recycle
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_copy_bitmap
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Bitmap_native_1copy_1bitmap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_get_pixels
 * Signature: (J[IIIIIII)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Bitmap_native_1get_1pixels
  (JNIEnv *, jclass, jlong, jintArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_copy_to_buffer
 * Signature: (JLjava/nio/Buffer;II)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Bitmap_native_1copy_1to_1buffer
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_save_to_png
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_android_graphics_Bitmap_native_1save_1to_1png
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_set_pixels
 * Signature: (J[IIIIIII)V
 */
JNIEXPORT void JNICALL Java_android_graphics_Bitmap_native_1set_1pixels
  (JNIEnv *, jclass, jlong, jintArray, jint, jint, jint, jint, jint, jint);

/*
 * Class:     android_graphics_Bitmap
 * Method:    native_get_pixels_ptr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_android_graphics_Bitmap_native_1get_1pixels_1ptr
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
