/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_graphics_BaseCanvas */

#ifndef _Included_android_graphics_BaseCanvas
#define _Included_android_graphics_BaseCanvas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawBitmap
 * Signature: (JJFFJIII)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawBitmap__JJFFJIII
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jlong, jint, jint, jint);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawBitmap
 * Signature: (JJFFFFFFFFJII)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawBitmap__JJFFFFFFFFJII
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong, jint, jint);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawBitmap
 * Signature: (J[IIIFFIIZJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawBitmap__J_3IIIFFIIZJ
  (JNIEnv *, jclass, jlong, jintArray, jint, jint, jfloat, jfloat, jint, jint, jboolean, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawColor
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawColor__JII
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawColor
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawColor__JJJI
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawPaint
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawPaint
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawPoint
 * Signature: (JFFJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawPoint
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawPoints
 * Signature: (J[FIIJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawPoints
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawLine
 * Signature: (JFFFFJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawLine
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawLines
 * Signature: (J[FIIJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawLines
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jint, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawRect
 * Signature: (JFFFFJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawRect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawOval
 * Signature: (JFFFFJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawOval
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawCircle
 * Signature: (JFFFJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawCircle
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawArc
 * Signature: (JFFFFFFZJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawArc
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jboolean, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawRoundRect
 * Signature: (JFFFFFFJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawRoundRect
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawShadow
 * Signature: (JFFFFFFFFFFII)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawShadow
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jint, jint);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawDoubleRoundRect
 * Signature: (JFFFFFFFFFFFFJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawDoubleRoundRect__JFFFFFFFFFFFFJ
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawDoubleRoundRect
 * Signature: (JFFFF[FFFFF[FJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawDoubleRoundRect__JFFFF_3FFFFF_3FJ
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloatArray, jfloat, jfloat, jfloat, jfloat, jfloatArray, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawPath
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawPath
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawRegion
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawRegion
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawBitmapMatrix
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawBitmapMatrix
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawBitmapMesh
 * Signature: (JJII[FI[IIJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawBitmapMesh
  (JNIEnv *, jclass, jlong, jlong, jint, jint, jfloatArray, jint, jintArray, jint, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawVertices
 * Signature: (JII[FI[FI[II[SIIJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawVertices
  (JNIEnv *, jclass, jlong, jint, jint, jfloatArray, jint, jfloatArray, jint, jintArray, jint, jshortArray, jint, jint, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawText
 * Signature: (J[CIIFFIJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawText__J_3CIIFFIJ
  (JNIEnv *, jclass, jlong, jcharArray, jint, jint, jfloat, jfloat, jint, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawText
 * Signature: (JLjava/lang/String;IIFFIJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawText__JLjava_lang_String_2IIFFIJ
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jfloat, jfloat, jint, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawTextRun
 * Signature: (JLjava/lang/String;IIIIFFZJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawTextRun__JLjava_lang_String_2IIIIFFZJ
  (JNIEnv *, jclass, jlong, jstring, jint, jint, jint, jint, jfloat, jfloat, jboolean, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawTextRun
 * Signature: (J[CIIIIFFZJJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawTextRun__J_3CIIIIFFZJJ
  (JNIEnv *, jclass, jlong, jcharArray, jint, jint, jint, jint, jfloat, jfloat, jboolean, jlong, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawTextOnPath
 * Signature: (J[CIIJFFIJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawTextOnPath__J_3CIIJFFIJ
  (JNIEnv *, jclass, jlong, jcharArray, jint, jint, jlong, jfloat, jfloat, jint, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nDrawTextOnPath
 * Signature: (JLjava/lang/String;JFFIJ)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nDrawTextOnPath__JLjava_lang_String_2JFFIJ
  (JNIEnv *, jclass, jlong, jstring, jlong, jfloat, jfloat, jint, jlong);

/*
 * Class:     android_graphics_BaseCanvas
 * Method:    nPunchHole
 * Signature: (JFFFFFF)V
 */
JNIEXPORT void JNICALL Java_android_graphics_BaseCanvas_nPunchHole
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
