/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_opengl_EGLExt */

#ifndef _Included_android_opengl_EGLExt
#define _Included_android_opengl_EGLExt
#ifdef __cplusplus
extern "C" {
#endif
#undef android_opengl_EGLExt_EGL_CONTEXT_FLAGS_KHR
#define android_opengl_EGLExt_EGL_CONTEXT_FLAGS_KHR 12540L
#undef android_opengl_EGLExt_EGL_CONTEXT_MAJOR_VERSION_KHR
#define android_opengl_EGLExt_EGL_CONTEXT_MAJOR_VERSION_KHR 12440L
#undef android_opengl_EGLExt_EGL_CONTEXT_MINOR_VERSION_KHR
#define android_opengl_EGLExt_EGL_CONTEXT_MINOR_VERSION_KHR 12539L
#undef android_opengl_EGLExt_EGL_OPENGL_ES3_BIT_KHR
#define android_opengl_EGLExt_EGL_OPENGL_ES3_BIT_KHR 64L
#undef android_opengl_EGLExt_EGL_RECORDABLE_ANDROID
#define android_opengl_EGLExt_EGL_RECORDABLE_ANDROID 12610L
/*
 * Class:     android_opengl_EGLExt
 * Method:    native_eglPresentationTimeANDROID
 * Signature: (JJJ)Z
 */
JNIEXPORT jboolean JNICALL Java_android_opengl_EGLExt_native_1eglPresentationTimeANDROID
  (JNIEnv *, jclass, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
