/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_hardware_Camera */

#ifndef _Included_android_hardware_Camera
#define _Included_android_hardware_Camera
#ifdef __cplusplus
extern "C" {
#endif
#undef android_hardware_Camera_CAMERA_ERROR_UNKNOWN
#define android_hardware_Camera_CAMERA_ERROR_UNKNOWN 1L
#undef android_hardware_Camera_CAMERA_ERROR_EVICTED
#define android_hardware_Camera_CAMERA_ERROR_EVICTED 2L
#undef android_hardware_Camera_CAMERA_ERROR_SERVER_DIED
#define android_hardware_Camera_CAMERA_ERROR_SERVER_DIED 100L
#undef android_hardware_Camera_PREVIEW_CB_NONE
#define android_hardware_Camera_PREVIEW_CB_NONE 0L
#undef android_hardware_Camera_PREVIEW_CB_EVERY_FRAME
#define android_hardware_Camera_PREVIEW_CB_EVERY_FRAME 1L
#undef android_hardware_Camera_PREVIEW_CB_ONE_SHOT
#define android_hardware_Camera_PREVIEW_CB_ONE_SHOT 2L
#undef android_hardware_Camera_PREVIEW_CB_WITH_BUFFER
#define android_hardware_Camera_PREVIEW_CB_WITH_BUFFER 3L
/*
 * Class:     android_hardware_Camera
 * Method:    native_getNumberOfCameras
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_android_hardware_Camera_native_1getNumberOfCameras
  (JNIEnv *, jclass);

/*
 * Class:     android_hardware_Camera
 * Method:    native_getCameraInfo
 * Signature: (ILandroid/hardware/Camera/CameraInfo;)V
 */
JNIEXPORT void JNICALL Java_android_hardware_Camera_native_1getCameraInfo
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     android_hardware_Camera
 * Method:    native_open
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_android_hardware_Camera_native_1open
  (JNIEnv *, jobject, jint);

/*
 * Class:     android_hardware_Camera
 * Method:    native_release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_hardware_Camera_native_1release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_hardware_Camera
 * Method:    native_setPreviewSurface
 * Signature: (JLandroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_android_hardware_Camera_native_1setPreviewSurface
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     android_hardware_Camera
 * Method:    native_setPreviewTexture
 * Signature: (JLandroid/graphics/SurfaceTexture;)V
 */
JNIEXPORT void JNICALL Java_android_hardware_Camera_native_1setPreviewTexture
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     android_hardware_Camera
 * Method:    native_setPreviewCallback
 * Signature: (JLandroid/hardware/Camera/PreviewCallback;I)V
 */
JNIEXPORT void JNICALL Java_android_hardware_Camera_native_1setPreviewCallback
  (JNIEnv *, jobject, jlong, jobject, jint);

/*
 * Class:     android_hardware_Camera
 * Method:    native_addCallbackBuffer
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_android_hardware_Camera_native_1addCallbackBuffer
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     android_hardware_Camera
 * Method:    native_startPreview
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_hardware_Camera_native_1startPreview
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_hardware_Camera
 * Method:    native_stopPreview
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_hardware_Camera_native_1stopPreview
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_hardware_Camera
 * Method:    native_getDefaultParameters
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_android_hardware_Camera_native_1getDefaultParameters
  (JNIEnv *, jobject, jlong);

/*
 * Class:     android_hardware_Camera
 * Method:    native_setParameters
 * Signature: (JIIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_android_hardware_Camera_native_1setParameters
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     android_hardware_Camera
 * Method:    native_setDisplayOrientation
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_android_hardware_Camera_native_1setDisplayOrientation
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
